module.exports = {
  allMarks: [
    { isMarked: 1, name: '优质客户' },
    { isMarked: 1, name: '好沟通' },
    { isMarked: 1, name: '自己开公司' },
    { isMarked: 1, name: '大好人' },
    { isMarked: 0, name: '男的' },
    { isMarked: 0, name: '技术员' },
    { isMarked: 0, name: '山炮' },
    { isMarked: 0, name: '精神病' },
    { isMarked: 0, name: '从西藏来的' },
  ],
  transText: '我是被转换过来的!',
  translate: 'Nice to meet you!',
  emotions: [
    [
      { name: '色', title: '/sexy', src: '/static/emotions/0.png' },
      { name: '大笑', title: '/haha', src: '/static/emotions/1.png' },
      { name: '发怒', title: '/angry', src: '/static/emotions/2.png' },
      { name: '微笑', title: '/smile', src: '/static/emotions/3.png' },
    ],
    [
      { name: '眼瞎', title: '/blind', src: '/static/emotions/4.png' },
      { name: '惊吓', title: '/scared', src: '/static/emotions/5.png' },
    ],
  ],
  userDetail: [
    {
      name: '张三',
      mobile: 18612345678,
      publicCode: '整点财经',
      focusState: '已关注',
      serviceId: 0,
      groupId: 0,
      firstFocus: '2018-02-12',
      source: '扫描二维码',
      tips: '人还可以，持续关注中',
      location: '浙江省杭州市拱墅区大关街道118号',
      lastTime: '2018-7-29 14:28:50',
      id: 0,
      portrait: '/static/imgs/1.jpg',
      times: 10,
    },
    {
      name: '王五',
      mobile: 18612345678,
      publicCode: '整点财经',
      focusState: '未关注',
      serviceId: 1,
      groupId: 1,
      firstFocus: '2018-02-12',
      source: '扫描二维码',
      tips: '人还可以，持续关注中',
      location: '浙江省杭州市拱墅区大关街道118号',
      lastTime: '2018-7-29 14:28:50',
      id: 1,
      portrait: '/static/imgs/2.jpg',
      times: 10,
    },
    {
      name: 'David',
      mobile: 18612345678,
      publicCode: '整点财经',
      focusState: '未关注',
      serviceId: 2,
      groupId: 2,
      firstFocus: '2018-02-12',
      source: '扫描二维码',
      tips: '人还可以，持续关注中',
      location: '浙江省杭州市拱墅区大关街道118号',
      lastTime: '2018-7-29 14:28:50',
      id: 2,
      portrait: '/static/imgs/3.jpg',
      times: 10,
    },
    {
      name: '王宇',
      mobile: 18612345678,
      publicCode: '整点财经',
      focusState: '未关注',
      serviceId: 1,
      firstFocus: '2018-02-12',
      source: '扫描二维码',
      tips: '人还可以，持续关注中',
      location: '浙江省杭州市拱墅区大关街道118号',
      lastTime: '2018-7-29 14:28:50',
      id: 3,
      portrait: '/static/imgs/4.jpg',
      times: 10,
    },
    {
      name: 'wangwu',
      mobile: 18612345678,
      publicCode: '整点财经',
      focusState: '未关注',
      serviceId: 0,
      firstFocus: '2018-02-12',
      source: '扫描二维码',
      tips: '人还可以，持续关注中',
      location: '浙江省杭州市拱墅区大关街道118号',
      lastTime: '2018-7-29 14:28:50',
      id: 4,
      portrait: '/static/imgs/5.jpg',
      times: 10,
    },
    {
      name: '王武骑',
      mobile: 18612345678,
      publicCode: '整点财经',
      focusState: '未关注',
      serviceId: 0,
      firstFocus: '2018-02-12',
      source: '扫描二维码',
      tips: '人还可以，持续关注中',
      location: '浙江省杭州市拱墅区大关街道118号',
      lastTime: '2018-7-29 14:28:50',
      id: 5,
      portrait: '/static/imgs/1.jpg',
      times: 10,
    },
    {
      name: 'hello',
      mobile: 18612345678,
      publicCode: '整点财经',
      focusState: '未关注',
      serviceId: 0,
      firstFocus: '2018-02-12',
      source: '扫描二维码',
      tips: '人还可以，持续关注中',
      location: '浙江省杭州市拱墅区大关街道118号',
      lastTime: '2018-7-29 14:28:50',
      id: 6,
      portrait: '/static/imgs/1.jpg',
      times: 10,
    },
    {
      name: 'david',
      mobile: 18612345678,
      publicCode: '整点财经',
      focusState: '未关注',
      serviceId: 0,
      firstFocus: '2018-02-12',
      source: '扫描二维码',
      tips: '人还可以，持续关注中',
      location: '浙江省杭州市拱墅区大关街道118号',
      lastTime: '2018-7-29 14:28:50',
      id: 7,
      portrait: '/static/imgs/1.jpg',
      times: 10,
    },
    {
      name: '政治',
      mobile: 18612345678,
      publicCode: '整点财经',
      focusState: '未关注',
      serviceId: 0,
      firstFocus: '2018-02-12',
      source: '扫描二维码',
      tips: '人还可以，持续关注中',
      location: '浙江省杭州市拱墅区大关街道118号',
      lastTime: '2018-7-29 14:28:50',
      id: 8,
      portrait: '/static/imgs/1.jpg',
      times: 10,
    },
    {
      name: '王琦',
      mobile: 18612345678,
      publicCode: '整点财经',
      focusState: '未关注',
      serviceId: 0,
      firstFocus: '2018-02-12',
      source: '扫描二维码',
      tips: '人还可以，持续关注中',
      location: '浙江省杭州市拱墅区大关街道118号',
      lastTime: '2018-7-29 14:28:50',
      id: 9,
      portrait: '/static/imgs/1.jpg',
      times: 10,
    },
    {
      name: '忘记送',
      mobile: 18612345678,
      publicCode: '整点财经',
      focusState: '未关注',
      serviceId: 0,
      firstFocus: '2018-02-12',
      source: '扫描二维码',
      tips: '人还可以，持续关注中',
      location: '浙江省杭州市拱墅区大关街道118号',
      lastTime: '2018-7-29 14:28:50',
      id: 10,
      portrait: '/static/imgs/1.jpg',
      times: 10,
    },
    {
      name: '咖色',
      mobile: 18612345678,
      publicCode: '整点财经',
      focusState: '未关注',
      serviceId: 0,
      firstFocus: '2018-02-12',
      source: '扫描二维码',
      tips: '人还可以，持续关注中',
      location: '浙江省杭州市拱墅区大关街道118号',
      lastTime: '2018-7-29 14:28:50',
      id: 11,
      portrait: '/static/imgs/1.jpg',
      times: 10,
    },
    {
      name: 'david',
      mobile: 18612345678,
      publicCode: '整点财经',
      focusState: '未关注',
      serviceId: 0,
      firstFocus: '2018-02-12',
      source: '扫描二维码',
      tips: '人还可以，持续关注中',
      location: '浙江省杭州市拱墅区大关街道118号',
      lastTime: '2018-7-29 14:28:50',
      id: 12,
      portrait: '/static/imgs/1.jpg',
      times: 10,
    },
    {
      name: '政治',
      mobile: 18612345678,
      publicCode: '整点财经',
      focusState: '未关注',
      serviceId: 0,
      firstFocus: '2018-02-12',
      source: '扫描二维码',
      tips: '人还可以，持续关注中',
      location: '浙江省杭州市拱墅区大关街道118号',
      lastTime: '2018-7-29 14:28:50',
      id: 13,
      portrait: '/static/imgs/1.jpg',
      times: 10,
    },
    {
      name: '王琦',
      mobile: 18612345678,
      publicCode: '整点财经',
      focusState: '未关注',
      serviceId: 0,
      firstFocus: '2018-02-12',
      source: '扫描二维码',
      tips: '人还可以，持续关注中',
      location: '浙江省杭州市拱墅区大关街道118号',
      lastTime: '2018-7-29 14:28:50',
      id: 14,
      portrait: '/static/imgs/1.jpg',
      times: 10,
    },
    {
      name: '忘记送',
      mobile: 18612345678,
      publicCode: '整点财经',
      focusState: '未关注',
      serviceId: 0,
      firstFocus: '2018-02-12',
      source: '扫描二维码',
      tips: '人还可以，持续关注中',
      location: '浙江省杭州市拱墅区大关街道118号',
      lastTime: '2018-7-29 14:28:50',
      id: 15,
      portrait: '/static/imgs/1.jpg',
      times: 10,
    },
    {
      name: '咖色',
      mobile: 18612345678,
      publicCode: '整点财经',
      focusState: '未关注',
      serviceId: 0,
      firstFocus: '2018-02-12',
      source: '扫描二维码',
      tips: '人还可以，持续关注中',
      location: '浙江省杭州市拱墅区大关街道118号',
      lastTime: '2018-7-29 14:28:50',
      id: 16,
      portrait: '/static/imgs/1.jpg',
      times: 10,
    },
    {
      name: 'david',
      mobile: 18612345678,
      publicCode: '整点财经',
      focusState: '未关注',
      serviceId: 0,
      firstFocus: '2018-02-12',
      source: '扫描二维码',
      tips: '人还可以，持续关注中',
      location: '浙江省杭州市拱墅区大关街道118号',
      lastTime: '2018-7-29 14:28:50',
      id: 17,
      portrait: '/static/imgs/1.jpg',
      times: 10,
    },
    {
      name: '政治',
      mobile: 18612345678,
      publicCode: '整点财经',
      focusState: '未关注',
      serviceId: 0,
      firstFocus: '2018-02-12',
      source: '扫描二维码',
      tips: '人还可以，持续关注中',
      location: '浙江省杭州市拱墅区大关街道118号',
      lastTime: '2018-7-29 14:28:50',
      id: 18,
      portrait: '/static/imgs/1.jpg',
      times: 10,
    },
    {
      name: '王琦',
      mobile: 18612345678,
      publicCode: '整点财经',
      focusState: '未关注',
      serviceId: 0,
      firstFocus: '2018-02-12',
      source: '扫描二维码',
      tips: '人还可以，持续关注中',
      location: '浙江省杭州市拱墅区大关街道118号',
      lastTime: '2018-7-29 14:28:50',
      id: 19,
      portrait: '/static/imgs/1.jpg',
      times: 10,
    },
    {
      name: '忘记送',
      mobile: 18612345678,
      publicCode: '整点财经',
      focusState: '未关注',
      serviceId: 0,
      firstFocus: '2018-02-12',
      source: '扫描二维码',
      tips: '人还可以，持续关注中',
      location: '浙江省杭州市拱墅区大关街道118号',
      lastTime: '2018-7-29 14:28:50',
      id: 20,
      portrait: '/static/imgs/1.jpg',
      times: 10,
    },
    {
      name: '咖色',
      mobile: 18612345678,
      publicCode: '整点财经',
      focusState: '未关注',
      serviceId: 0,
      firstFocus: '2018-02-12',
      source: '扫描二维码',
      tips: '人还可以，持续关注中',
      location: '浙江省杭州市拱墅区大关街道118号',
      lastTime: '2018-7-29 14:28:50',
      id: 21,
      portrait: '/static/imgs/1.jpg',
      times: 10,
    },
    {
      name: 'david',
      mobile: 18612345678,
      publicCode: '整点财经',
      focusState: '未关注',
      serviceId: 0,
      firstFocus: '2018-02-12',
      source: '扫描二维码',
      tips: '人还可以，持续关注中',
      location: '浙江省杭州市拱墅区大关街道118号',
      lastTime: '2018-7-29 14:28:50',
      id: 22,
      portrait: '/static/imgs/1.jpg',
      times: 10,
    },
    {
      name: '政治',
      mobile: 18612345678,
      publicCode: '整点财经',
      focusState: '未关注',
      serviceId: 0,
      firstFocus: '2018-02-12',
      source: '扫描二维码',
      tips: '人还可以，持续关注中',
      location: '浙江省杭州市拱墅区大关街道118号',
      lastTime: '2018-7-29 14:28:50',
      id: 23,
      portrait: '/static/imgs/1.jpg',
      times: 10,
    },
    {
      name: '王琦',
      mobile: 18612345678,
      publicCode: '整点财经',
      focusState: '未关注',
      serviceId: 0,
      firstFocus: '2018-02-12',
      source: '扫描二维码',
      tips: '人还可以，持续关注中',
      location: '浙江省杭州市拱墅区大关街道118号',
      lastTime: '2018-7-29 14:28:50',
      id: 24,
      portrait: '/static/imgs/1.jpg',
      times: 10,
    },
    {
      name: '忘记送',
      mobile: 18612345678,
      publicCode: '整点财经',
      focusState: '未关注',
      serviceId: 0,
      firstFocus: '2018-02-12',
      source: '扫描二维码',
      tips: '人还可以，持续关注中',
      location: '浙江省杭州市拱墅区大关街道118号',
      lastTime: '2018-7-29 14:28:50',
      id: 25,
      portrait: '/static/imgs/1.jpg',
      times: 10,
    },
    {
      name: '咖色',
      mobile: 18612345678,
      publicCode: '整点财经',
      focusState: '未关注',
      serviceId: 0,
      firstFocus: '2018-02-12',
      source: '扫描二维码',
      tips: '人还可以，持续关注中',
      location: '浙江省杭州市拱墅区大关街道118号',
      lastTime: '2018-7-29 14:28:50',
      id: 26,
      portrait: '/static/imgs/1.jpg',
      times: 10,
    },
    {
      name: 'david',
      mobile: 18612345678,
      publicCode: '整点财经',
      focusState: '未关注',
      serviceId: 0,
      firstFocus: '2018-02-12',
      source: '扫描二维码',
      tips: '人还可以，持续关注中',
      location: '浙江省杭州市拱墅区大关街道118号',
      lastTime: '2018-7-29 14:28:50',
      id: 27,
      portrait: '/static/imgs/1.jpg',
      times: 10,
    },
    {
      name: '政治',
      mobile: 18612345678,
      publicCode: '整点财经',
      focusState: '未关注',
      serviceId: 0,
      firstFocus: '2018-02-12',
      source: '扫描二维码',
      tips: '人还可以，持续关注中',
      location: '浙江省杭州市拱墅区大关街道118号',
      lastTime: '2018-7-29 14:28:50',
      id: 28,
      portrait: '/static/imgs/1.jpg',
      times: 10,
    },
    {
      name: '王琦',
      mobile: 18612345678,
      publicCode: '整点财经',
      focusState: '未关注',
      serviceId: 0,
      firstFocus: '2018-02-12',
      source: '扫描二维码',
      tips: '人还可以，持续关注中',
      location: '浙江省杭州市拱墅区大关街道118号',
      lastTime: '2018-7-29 14:28:50',
      id: 29,
      portrait: '/static/imgs/1.jpg',
      times: 10,
    },
    {
      name: '忘记送',
      mobile: 18612345678,
      publicCode: '整点财经',
      focusState: '未关注',
      serviceId: 0,
      firstFocus: '2018-02-12',
      source: '扫描二维码',
      tips: '人还可以，持续关注中',
      location: '浙江省杭州市拱墅区大关街道118号',
      lastTime: '2018-7-29 14:28:50',
      id: 30,
      portrait: '/static/imgs/1.jpg',
      times: 10,
    },
    {
      name: '咖色',
      mobile: 18612345678,
      publicCode: '整点财经',
      focusState: '未关注',
      serviceId: 0,
      firstFocus: '2018-02-12',
      source: '扫描二维码',
      tips: '人还可以，持续关注中',
      location: '浙江省杭州市拱墅区大关街道118号',
      lastTime: '2018-7-29 14:28:50',
      id: 31,
      portrait: '/static/imgs/1.jpg',
      times: 10,
    },
  ],
  services: {
    0: '金牌客服1',
    1: '金牌客服2',
    2: '金牌客服3',
    3: '金牌客服4',
    4: '普通客服1',
    5: '普通客服2',
    6: '普通客服3',
  },
  models: [
    {
      template_list: [
        {
          template_id: 'LHLJDSLlOVKn5GrTFpncEYTojx6ddbt8WYoV5s',
          title: '订单已接受',
          primary_industry: 'IT科技',
          deputy_industry: '互联网|电子商务',
          content:
            '{ {result.DATA} }\n\n订单金额:{ {withdrawMoney.DATA} }\n接受  时间:{ {withdrawTime.DATA} }\n银行信息:{ {cardInfo.DATA} }\n到账时间:  { {arrivedTime.DATA} }\n{ {remark.DATA} }',
          example:
            '您已提交订单申请\n\n订单金额：xxxx元\n订单时间：2013-10-10 12:22:22\n银行信息：xx银行(尾号xxxx)\n到账时间：预计xxxxxxx\n\n预计将于xxxx到达您的银行卡',
        },
      ],
    },
    {
      template_list: [
        {
          template_id: 'SLJFLSGrTFpncEYTojx6ddbt8WYoV5s',
          title: '订单失败',
          primary_industry: 'IT科技',
          deputy_industry: '互联网|电子商务',
          content:
            '{ {result.DATA} }\n\n领奖金额:{ {withdrawMoney.DATA} }\n领奖  时间:{ {withdrawTime.DATA} }\n银行信息:{ {cardInfo.DATA} }\n到账时间:  { {arrivedTime.DATA} }\n{ {remark.DATA} }',
          example:
            '您已提交领奖申请\n\n领奖金额：xxxx元\n领奖时间：2013-10-10 12:22:22\n银行信息：xx银行(尾号xxxx)\n到账时间：预计xxxxxxx\n\n预计将于xxxx到达您的银行卡',
        },
      ],
    },
    {
      template_list: [
        {
          template_id: 'OWHOFDNKn5GrTFpncEYTojx6ddbt8WYoV5s',
          title: '订单成功',
          primary_industry: '制造业',
          deputy_industry: '互联网|电子商务',
          content:
            '{ {result.DATA} }\n\n顶顶那金额:{ {withdrawMoney.DATA} }\n领奖  时间:{ {withdrawTime.DATA} }\n银行信息:{ {cardInfo.DATA} }\n到账时间:  { {arrivedTime.DATA} }\n{ {remark.DATA} }',
          example:
            '您已提交领奖申请\n\n领奖金额：xxxx元\n领奖时间：2013-10-10 12:22:22\n银行信息：xx银行(尾号xxxx)\n到账时间：预计xxxxxxx\n\n预计将于xxxx到达您的银行卡',
        },
      ],
    },
    {
      template_list: [
        {
          template_id: 'LJDLDSDDDlOVKn5GrTFpncEYTojx6ddbt8WYoV5s',
          title: '订单处理中',
          primary_industry: 'IT科技',
          deputy_industry: '互联网|电子商务',
          content:
            '{ {result.DATA} }\n\n领奖金额:{ {withdrawMoney.DATA} }\n领奖  时间:{ {withdrawTime.DATA} }\n银行信息:{ {cardInfo.DATA} }\n到账时间:  { {arrivedTime.DATA} }\n{ {remark.DATA} }',
          example:
            '您已提交领奖申请\n\n领奖金额：xxxx元\n领奖时间：2013-10-10 12:22:22\n银行信息：xx银行(尾号xxxx)\n到账时间：预计xxxxxxx\n\n预计将于xxxx到达您的银行卡',
        },
      ],
    },
    {
      template_list: [
        {
          template_id: ':LSKMGV:SMVBlOVKn5GrTFpncEYTojx6ddbt8WYoV5s',
          title: '订单已处理',
          primary_industry: 'IT科技',
          deputy_industry: '互联网|电子商务',
          content:
            '{ {result.DATA} }\n\n领奖金额:{ {withdrawMoney.DATA} }\n领奖  时间:{ {withdrawTime.DATA} }\n银行信息:{ {cardInfo.DATA} }\n到账时间:  { {arrivedTime.DATA} }\n{ {remark.DATA} }',
          example:
            '您已提交领奖申请\n\n领奖金额：xxxx元\n领奖时间：2013-10-10 12:22:22\n银行信息：xx银行(尾号xxxx)\n到账时间：预计xxxxxxx\n\n预计将于xxxx到达您的银行卡',
        },
      ],
    },
  ],
  groups: {
    0: '组一',
    1: '组二',
    2: '组三',
    3: '组四',
    4: '组五',
    5: '组六',
    6: '组七',
  },
  picText: {},
  searchTypes: [
    {
      type: 0,
      name: '最近联系人',
    },
    {
      type: 1,
      name: '等待粉丝回复',
    },
    {
      type: 2,
      name: '即将脱离活跃',
    },
    {
      type: 3,
      name: '刚刚脱离活跃',
    },
  ],
  records: [
    {
      name: '张三',
      info: 'HI,很高兴认识你,HI,很高兴认识你很高兴认识你',
      type: 0,
      len: 9,
      id: 0,
      isTop: true,
      setTopTime: 123,
      chatTime: 1533153730,
      searchType: 0,
      msgType: 0,
    },
    {
      name: '王五',
      info: '我也是',
      type: 1,
      len: 2,
      isTop: true,
      setTopTime: 123432,
      id: 1,
      chatTime: 1533154730,
      searchType: 0,
      msgType: 0,
    },
    {
      name: 'David',
      info:
        '你看见啦水力发3电看见路上看见【】士大夫十分立刻哦罚款的说法是防水房但是服务网点光辐射大概是个温柔可以把我带上吗',
      type: 0,
      len: 2,
      id: 2,
      chatTime: 1533155730,
      searchType: 0,
      msgType: 0,
    },
    {
      name: '王宇',
      info: '在不在？',
      type: 0,
      len: 2,
      id: 3,
      chatTime: 1533156730,
      searchType: 0,
      msgType: 0,
    },
    {
      name: 'wangwu',
      info: '后来我埃里克就是大佛骗我飞机配阿韦杰夫拉开点距离拍摄 怕了科技发达普拉斯飓风琳达设计费',
      type: 0,
      len: 6,
      id: 4,
      chatTime: 1533157730,
      searchType: 1,
      msgType: 0,
    },
    {
      name: '王武骑',
      info: '就all法律手段维埃帕杜拉老妈概率高达十六安康健身房的饭卡设立了干嘛',
      type: 1,
      len: 2,
      id: 5,
      chatTime: 1533158730,
      searchType: 1,
      msgType: 0,
    },
    {
      name: 'hello',
      info: '虑离开单独收费频道你',
      type: 0,
      len: 2,
      id: 6,
      chatTime: 1533159730,
      searchType: 1,
      msgType: 0,
    },
    {
      name: 'david',
      info: '我也是',
      type: 1,
      len: 2,
      id: 7,
      chatTime: 1533165730,
      searchType: 1,
      msgType: 0,
    },
    {
      name: '政治',
      info: '你法是防水房但是服务网点电看见路上看见【】士大夫十分',
      type: 0,
      len: 2,
      id: 8,
      chatTime: 1533175730,
      searchType: 2,
      msgType: 0,
    },
    {
      name: '王琦',
      info: '现场v学生的',
      type: 0,
      len: 2,
      id: 9,
      chatTime: 1533185730,
      searchType: 2,
      msgType: 0,
    },
    {
      name: '忘记送',
      info: '后来我埃里克就是大',
      type: 0,
      len: 2,
      id: 10,
      chatTime: 1533195730,
      searchType: 2,
      msgType: 0,
    },
    {
      name: '咖色',
      info: '恢复大',
      type: 1,
      len: 2,
      id: 11,
      chatTime: 1533265730,
      searchType: 4,
      msgType: 0,
    },
    {
      name: 'david',
      info: '我也是',
      type: 1,
      len: 2,
      id: 12,
      chatTime: 1533165730,
      searchType: 1,
      msgType: 0,
    },
    {
      name: '政治',
      info: '你法是防水房但是服务网点电看见路上看见【】士大夫十分',
      type: 0,
      len: 2,
      id: 13,
      chatTime: 1533175730,
      searchType: 2,
      msgType: 0,
    },
    {
      name: '王琦',
      info: '现场v学生的',
      type: 0,
      len: 2,
      id: 14,
      chatTime: 1533185730,
      searchType: 2,
      msgType: 0,
    },
    {
      name: '忘记送',
      info: '后来我埃里克就是大',
      type: 0,
      len: 2,
      id: 15,
      chatTime: 1533195730,
      searchType: 2,
      msgType: 0,
    },
    {
      name: '咖色',
      info: '恢复大',
      type: 1,
      len: 2,
      id: 16,
      chatTime: 1533265730,
      searchType: 4,
      msgType: 0,
    },
    {
      name: 'david',
      info: '我也是',
      type: 1,
      len: 2,
      id: 17,
      chatTime: 1533165730,
      searchType: 1,
      msgType: 0,
    },
    {
      name: '政治',
      info: '你法是防水房但是服务网点电看见路上看见【】士大夫十分',
      type: 0,
      len: 2,
      id: 18,
      chatTime: 1533175730,
      searchType: 2,
      msgType: 0,
    },
    {
      name: '王琦',
      info: '现场v学生的',
      type: 0,
      len: 2,
      id: 19,
      chatTime: 1533185730,
      searchType: 2,
      msgType: 0,
    },
    {
      name: '忘记送',
      info: '后来我埃里克就是大',
      type: 0,
      len: 2,
      id: 20,
      chatTime: 1533195730,
      searchType: 2,
      msgType: 0,
    },
    {
      name: '咖色',
      info: '恢复大',
      type: 1,
      len: 2,
      id: 21,
      chatTime: 1533265730,
      searchType: 4,
      msgType: 0,
    },
    {
      name: 'david',
      info: '我也是',
      type: 1,
      len: 2,
      id: 22,
      chatTime: 1533165730,
      searchType: 1,
      msgType: 0,
    },
    {
      name: '政治',
      info: '你法是防水房但是服务网点电看见路上看见【】士大夫十分',
      type: 0,
      len: 2,
      id: 23,
      chatTime: 1533175730,
      searchType: 2,
      msgType: 0,
    },
    {
      name: '王琦',
      info: '现场v学生的',
      type: 0,
      len: 2,
      id: 24,
      chatTime: 1533185730,
      searchType: 2,
      msgType: 0,
    },
    {
      name: '忘记送',
      info: '后来我埃里克就是大',
      type: 0,
      len: 2,
      id: 25,
      chatTime: 1533195730,
      searchType: 2,
      msgType: 0,
    },
    {
      name: '咖色',
      info: '恢复大',
      type: 1,
      len: 2,
      id: 26,
      chatTime: 1533265730,
      searchType: 4,
      msgType: 0,
    },
    {
      name: 'david',
      info: '我也是',
      type: 1,
      len: 2,
      id: 27,
      chatTime: 1533165730,
      searchType: 1,
      msgType: 0,
    },
    {
      name: '政治',
      info: '你法是防水房但是服务网点电看见路上看见【】士大夫十分',
      type: 0,
      len: 2,
      id: 28,
      chatTime: 1533175730,
      searchType: 2,
      msgType: 0,
    },
    {
      name: '王琦',
      info: '现场v学生的',
      type: 0,
      len: 2,
      id: 29,
      chatTime: 1533185730,
      searchType: 2,
      msgType: 0,
    },
    {
      name: '忘记送',
      info: '后来我埃里克就是大',
      type: 0,
      len: 2,
      id: 30,
      chatTime: 1533195730,
      searchType: 2,
      msgType: 0,
    },
    {
      name: '咖色',
      info: '恢复大',
      type: 1,
      len: 2,
      id: 31,
      chatTime: 1533265730,
      searchType: 4,
      msgType: 0,
    },
  ],
  source0: {
    imgs: [
      {
        name: '分组1',
        groundId: 0,
        arr: [
          { info: '/static/imgs/1.jpg', id: 0, msgType: 1, infoType: 0 },
          { info: '/static/imgs/2.jpg', id: 1, msgType: 1, infoType: 0 },
          { info: '/static/imgs/3.jpg', id: 2, msgType: 1, infoType: 0 },
          { info: '/static/imgs/4.jpg', id: 3, msgType: 1, infoType: 0 },
        ],
      },
      {
        name: '分组2',
        groundId: 0,
        arr: [{ info: '/static/imgs/5.jpg', groupId: 1, id: 4, msgType: 1, infoType: 0 }],
      },
    ],
    links: [
      {
        name: '分组1',
        groundId: 0,
        arr: [
          {
            name: '我',
            type: 1,
            infoType: 0,
            msgType: 6,
            id: 51,
            chatTime: 1533260730,
            info: [
              {
                info: '/static/imgs/1.jpg',
                title: '进垃圾堆了',
                content: '今山东分局哦我就饿哦极乐世界的富婆视频和教师辅导辅导和',
                msgType: 6,
                infoType: 0,
                id: 511,
              },
              {
                info: '/static/imgs/3.jpg',
                title: '进垃圾堆了',
                content: '是公司鬼斧神工三个都是更好地发挥的好的人同样',
                msgType: 6,
                infoType: 0,
                id: 512,
              },
              {
                info: '/static/imgs/4.jpg',
                title: '进垃圾堆了',
                content: '是公司鬼斧神工三个都是更好地发挥的好的人同样',
                msgType: 6,
                infoType: 0,
                id: 513,
              },
            ],
          },
          {
            name: '我',
            type: 1,
            infoType: 0,
            msgType: 6,
            id: 61,
            chatTime: 1533260730,
            info: [
              {
                info: '/static/imgs/2.jpg',
                title: '进垃圾堆了',
                content: '今山东分局哦我就饿哦极乐世界的富婆视频和教师辅导辅导和',
                msgType: 6,
                infoType: 0,
                id: 611,
              },
              {
                info: '/static/imgs/2.jpg',
                title: '进垃圾堆了',
                content: '是公司鬼斧神工三个都是更好地发挥的好的人同样',
                msgType: 6,
                infoType: 0,
                id: 612,
              },
            ],
          },
        ],
      },
      {
        name: '分组3',
        groundId: 0,
        arr: [
          {
            name: '我',
            type: 1,
            infoType: 0,
            msgType: 6,
            id: 711,
            chatTime: 1533260730,
            info: [
              {
                info: '/static/imgs/3.jpg',
                title: '进垃圾堆了',
                content: '今山东分局哦我就饿哦极乐世界的富婆视频和教师辅导辅导和',
                msgType: 6,
                infoType: 0,
                id: 711,
              },
              {
                info: '/static/imgs/1.jpg',
                title: '进垃圾堆了',
                content: '是公司鬼斧神工三个都是更好地发挥的好的人同样',
                msgType: 6,
                infoType: 0,
                id: 712,
              },
            ],
          },
        ],
      },
    ],
    audios: [
      {
        name: '分组1',
        groundId: 0,
        arr: [
          {
            url: '/static/audio/1.mp3',
            name: 'jskjoweojh.mp4',
            time: '未知时长',
            createTime: '2018年05月28日',
            id: 12,
            msgType: 3,
            infoType: 0,
          },
          {
            url: '/static/audio/1.mp3',
            name: 'jskjoweojh.mp4',
            time: '未知时长',
            createTime: '2018年05月28日',
            id: 13,
            msgType: 3,
            infoType: 0,
          },
          {
            url: '/static/audio/1.mp3',
            name: 'jskjoweojh.mp4',
            time: '未知时长',
            createTime: '2018年05月28日',
            id: 14,
            msgType: 3,
            infoType: 0,
          },
          {
            url: '/static/audio/1.mp3',
            name: 'jskjoweojh.mp4',
            time: '未知时长',
            createTime: '2018年05月28日',
            id: 15,
            msgType: 3,
            infoType: 0,
          },
        ],
      },
      {
        name: '分组2',
        groundId: 1,
        arr: [
          {
            url: '/static/audio/1.mp3',
            name: 'jskjoweojh.mp4',
            time: '未知时长',
            createTime: '2018年05月28日',
            id: 16,
            msgType: 3,
            infoType: 0,
          },
          {
            url: '/static/audio/1.mp3',
            name: 'jskjoweojh.mp4',
            time: '未知时长',
            createTime: '2018年05月28日',
            id: 17,
            msgType: 3,
            infoType: 0,
          },
        ],
      },
    ],
    videos: [
      {
        name: '分组1',
        groundId: 0,
        arr: [
          {
            info: { src: 'http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4' },
            id: 18,
            msgType: 4,
            infoType: 0,
          },
          {
            info: { src: 'http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4' },
            id: 19,
            msgType: 4,
            infoType: 0,
          },
          {
            info: { src: 'http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4' },
            id: 20,
            msgType: 4,
            infoType: 0,
          },
          {
            info: { src: 'http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4' },
            id: 21,
            msgType: 4,
            infoType: 0,
          },
        ],
      },
      {
        name: '分组2',
        groundId: 1,
        arr: [
          {
            info: { src: 'http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4' },
            id: 22,
            msgType: 4,
            infoType: 0,
          },
          {
            info: { src: 'http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4' },
            id: 23,
            msgType: 4,
            infoType: 0,
          },
          {
            info: { src: 'http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4' },
            id: 24,
            msgType: 4,
            infoType: 0,
          },
        ],
      },
    ],
  },
  source1: {
    imgs: [
      {
        name: '分组1',
        groundId: 0,
        arr: [{ info: '/static/imgs/3.jpg', id: 25 }, { info: '/static/imgs/4.jpg', id: 26 }],
      },
      { name: '分组2', groundId: 0, arr: [{ info: '/static/imgs/5.jpg', groupId: 1, id: 27 }] },
    ],
    links: [
      {
        name: '分组1',
        groundId: 0,
        arr: [
          {
            name: '我',
            type: 1,
            infoType: 0,
            msgType: 6,
            id: 51,
            chatTime: 1533260730,
            info: [
              {
                info: '/static/imgs/4.jpg',
                title: '进垃圾堆了',
                content: '是公司鬼斧神工三个都是更好地发挥的好的人同样',
                msgType: 6,
                infoType: 0,
                id: 513,
              },
            ],
          },
          {
            name: '我',
            type: 1,
            infoType: 0,
            msgType: 6,
            id: 61,
            chatTime: 1533260730,
            info: [
              {
                info: '/static/imgs/5.jpg',
                title: '进垃圾堆了',
                content: '今山东分局哦我就饿哦极乐世界的富婆视频和教师辅导辅导和',
                msgType: 6,
                infoType: 0,
                id: 611,
              },
              {
                info: '/static/imgs/1.jpg',
                title: '进垃圾堆了',
                content: '是公司鬼斧神工三个都是更好地发挥的好的人同样',
                msgType: 6,
                infoType: 0,
                id: 612,
              },
            ],
          },
        ],
      },
      {
        name: '分组2',
        groundId: 0,
        arr: [
          {
            name: '我',
            type: 1,
            infoType: 0,
            msgType: 6,
            id: 711,
            chatTime: 1533260730,
            info: [
              {
                info: '/static/imgs/3.jpg',
                title: '进垃圾堆了',
                content: '今山东分局哦我就饿哦极乐世界的富婆视频和教师辅导辅导和',
                msgType: 6,
                infoType: 0,
                id: 711,
              },
              {
                info: '/static/imgs/4.jpg',
                title: '进垃圾堆了',
                content: '是公司鬼斧神工三个都是更好地发挥的好的人同样',
                msgType: 6,
                infoType: 0,
                id: 712,
              },
            ],
          },
        ],
      },
    ],
    audios: [
      {
        name: '分组1',
        groundId: 0,
        arr: [
          {
            url: '/static/audio/1.mp3',
            name: 'jskjoweojh.mp4',
            time: '未知时长',
            createTime: '2018年05月28日',
            id: 30,
          },
        ],
      },
      {
        name: '分组2',
        groundId: 1,
        arr: [
          {
            url: '/static/audio/1.mp3',
            name: 'jskjoweojh.mp4',
            time: '未知时长',
            createTime: '2018年05月28日',
            id: 31,
          },
        ],
      },
    ],
    videos: [
      {
        name: '分组1',
        groundId: 0,
        arr: [{ info: { src: 'http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4' }, id: 32 }],
      },
      {
        name: '分组2',
        groundId: 1,
        arr: [{ info: { src: 'http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4' }, id: 33 }],
      },
    ],
  },
  latestContact: [
    {
      name: '张三',
      info: 'HI,很高兴认识你,HI,很高兴认识你很高兴认识你',
      type: 0,
      len: 9,
      id: 0,
      chatTime: 2013,
      isTop: true,
      topTime: 12,
    },
    {
      name: '王五',
      info: '我也是',
      type: 1,
      len: 2,
      id: 1,
      chatTime: 2017,
      isTop: true,
      topTime: 1,
    },
    {
      name: 'David',
      info:
        '你看见啦水力发电看见路上看见【】士大夫十分立刻哦罚款的说法是防水房但是服务网点光辐射大概是个温柔可以把我带上吗',
      type: 0,
      len: 2,
      id: 2,
      chatTime: 2015,
    },
    {
      name: '王宇',
      info: '在不在？',
      type: 0,
      len: 2,
      id: 3,
      chatTime: 2012,
    },
    {
      name: 'wangwu',
      info: '后来我埃里克就是大佛骗我飞机配阿韦杰夫拉开点距离拍摄 怕了科技发达普拉斯飓风琳达设计费',
      type: 0,
      len: 6,
      id: 4,
      chatTime: 2015,
    },
    {
      name: '王武骑',
      info: '就all法律手段维埃帕杜拉老妈概率高达十六安康健身房的饭卡设立了干嘛',
      type: 1,
      len: 2,
      id: 5,
      chatTime: 2013,
    },
  ],
  searchUser: [
    {
      name: '王五',
      info: '我也是',
      type: 1,
      len: 2,
      id: 1,
      chatTime: 2017,
      searchType: 0,
    },
    {
      name: '王宇',
      info: '在不在？',
      type: 0,
      len: 2,
      id: 3,
      chatTime: 2012,
      searchType: 0,
    },
    {
      name: 'wangwu',
      info: '后来我埃里克就是大佛骗我飞机配阿韦杰夫拉开点距离拍摄 怕了科技发达普拉斯飓风琳达设计费',
      type: 0,
      len: 6,
      id: 4,
      chatTime: 2015,
      searchType: 1,
    },
    {
      name: '王武骑',
      info: '就all法律手段维埃帕杜拉老妈概率高达十六安康健身房的饭卡设立了干嘛',
      type: 1,
      len: 2,
      id: 5,
      chatTime: 2013,
      searchType: 1,
    },
    {
      name: '王琦',
      info: '现场v学生的',
      type: 0,
      len: 2,
      id: 9,
      chatTime: 2016,
      searchType: 2,
    },
    {
      name: '忘记送',
      info: '后来我埃里克就是大',
      type: 0,
      len: 2,
      id: 10,
      chatTime: 2014,
      searchType: 2,
    },
  ],
  userPortrait: {
    name: '王鑫成',
    type: '管理员',
    publicCode: '',
    mobile: 15612345678,
    email: '234729040298@qq.com',
    apartment: '杭州某某某有限公司',
    xiwei: ['整点财经公众号', '粉丝册罗公众号客服', '某某消息公众号客服'],
  },
  allMarks1: [
    {
      groupId: 0,
      name: '客户意向',
      groupChoose: true,
      arr: [
        { id: 0, name: '已成交' },
        { id: 1, name: '有意向' },
        { id: 2, name: '没有意向' },
        { id: 3, name: '没有回应' },
        { id: 4, name: '等待沟通' },
        { id: 5, name: '好沟通' },
        { id: 6, name: '态度差' },
        { id: 7, name: '大帅哥' },
        { id: 8, name: '人品好' },
      ],
    },
    {
      groupId: 1,
      name: '所属行业',
      arr: [
        { id: 9, name: '医疗美容' },
        { id: 10, name: '婚纱摄影' },
        { id: 11, name: '教育培训' },
        { id: 12, name: '地产假装' },
        { id: 13, name: '餐饮娱乐' },
      ],
    },
    {
      groupId: 2,
      name: '公司规模',
      arr: [
        { id: 14, name: '10人一下' },
        { id: 15, name: '10-30人' },
        { id: 16, name: '30-50人' },
        { id: 17, name: '50-100人' },
        { id: 18, name: '1000人' },
      ],
    },
    {
      groupId: 3,
      name: '所属区域',
      arr: [
        { id: 19, name: '重庆市' },
        { id: 20, name: '杭州' },
        { id: 21, name: '北京' },
        { id: 22, name: '株洲' },
        { id: 23, name: '河南' },
      ],
    },
    {
      groupId: 4,
      name: '职业',
      arr: [
        { id: 24, name: 'IT' },
        { id: 25, name: '农业' },
        { id: 26, name: '养猪' },
        { id: 27, name: '制造业' },
        { id: 28, name: '互联网' },
      ],
    },
    {
      groupId: 5,
      name: '级别',
      arr: [
        { id: 29, name: '行政' },
        { id: 30, name: '部长' },
        { id: 31, name: '经理' },
        { id: 32, name: '总监' },
        { id: 33, name: '老板' },
      ],
    },
  ],
  chooseMark: [
    [
      { id: 0, name: '已成交' },
      { id: 5, name: '好沟通' },
      { id: 8, name: '人品好' },
      { id: 9, name: '医疗美容' },
    ],
    [{ id: 30, name: '部长' }],
    [{ id: 26, name: '养猪' }],
    [{ id: 20, name: '杭州' }, { id: 33, name: '老板' }],
  ],
  store: [
    {
      id: 0,
      name: '收藏分组1',
      msgs: [
        {
          name: '张三',
          info: '/static/imgs/5.jpg',
          type: 0,
          infoType: 0,
          msgType: 1,
          id: 6,
          chatTime: 1533260430,
        },
        {
          name: '我',
          info: '/static/audio/1.mp3',
          type: 1,
          infoType: 0,
          msgType: 3,
          id: 7,
          chatTime: 1533260530,
        },
        {
          name: '张三',
          info: {
            type: 'video/mp4',
            src: 'http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4',
            poster: 'https://surmon-china.github.io/vue-quill-editor/static/images/surmon-1.jpg',
          },
          type: 0,
          infoType: 0,
          msgType: 4,
          id: 8,
          chatTime: 1533260630,
        },
        {
          name: '张三',
          info: 'https://baidu.com',
          type: 0,
          infoType: 0,
          msgType: 5,
          id: 12,
          chatTime: 1533262730,
        },
        {
          name: '我',
          info: {
            title: '业务信息提醒',
            content:
              '<p>好消息，直播课今晚八点准时开课了，敬请关注</p><p>好消息，直播课今晚八点准时开课了，敬请关注</p>',
          },
          type: 1,
          infoType: 0,
          msgType: 2,
          id: 10,
          chatTime: 1533260730,
        },
        {
          name: '我',
          info: '我也是',
          type: 1,
          infoType: 0,
          msgType: 0,
          id: 1,
          chatTime: 1533260020,
        },
      ],
    },
    {
      id: 1,
      name: '收藏分组2',
      msgs: [
        {
          name: '张三',
          info: '/static/imgs/5.jpg',
          type: 0,
          infoType: 0,
          msgType: 1,
          id: 6,
          chatTime: 1533260430,
        },
        {
          name: '我',
          info: '我也是',
          type: 1,
          infoType: 0,
          msgType: 0,
          id: 1,
          chatTime: 1533260020,
        },
      ],
    },
  ],
  msgPortrait: {
    name: '',
    times: 10,
    publicNum: '正点财经',
    souce: '',
    location: '',
    lastTime: '2018-6-19 14:28:12',
    labels: [
      '优质潜力客户',
      '好沟通',
      '非常好',
      '自己开公司',
      '有趣',
      '经常出差，一般去澳洲，冬天去的多，夏天少一些',
    ],
  },
  fansChatList: [
    {
      name: 'hello',
      info: '虑离开单独收费频道你',
      type: 0,
    },
    {
      name: 'david',
      info: '我也是',
      type: 1,
    },
    {
      name: '政治',
      info: '你法是防水房但是服务网点电看见路上看见【】士大夫十分',
      type: 0,
    },
    {
      name: '王琦',
      info: '现场v学生的',
      type: 0,
    },
    {
      name: '忘记送',
      info: '后来我埃里克就是大',
      type: 0,
    },
    {
      name: '咖色',
      info: '恢复大',
      type: 1,
    },
  ],
  userInfo: {
    company: '杭州星客互联有限公司',
    name: '诚郡王',
    userType: '1',
    mobile: '13812345678',
    email: '1032304@qq.com',
    apartment: '财务部',
    xiwei: ['整点财经公众号客服', '粉丝策略公众号客服', '洋财信息公众号客服'],
  },
  chat0: {
    0: {
      name: '张三',
      info: '安康健身房的饭卡设立了干嘛',
      type: 0,
      infoType: 0,
      msgType: 0,
      id: 0,
      chatTime: 1533260010,
    },
    1: {
      name: '我',
      info: '我也是',
      type: 1,
      infoType: 0,
      msgType: 0,
      id: 1,
      chatTime: 1533260020,
    },
    2: {
      name: '粉丝轨迹',
      info: '粉丝轨迹 2018/7/20 星期日',
      infoType: 1,
      id: 2,
      chatTime: 1533260030,
    },
    3: {
      name: '张三',
      info: '/static/imgs/4.jpg',
      type: 0,
      id: 3,
      infoType: 0,
      msgType: 1,
      chatTime: 1533260130,
    },
    4: {
      name: '粉丝轨迹',
      info: '粉丝轨迹 2018/7/20 星期日',
      infoType: 1,
      id: 4,
      chatTime: 1533260230,
    },
    5: {
      name: '张三',
      info: '在不在？',
      type: 0,
      infoType: 0,
      msgType: 0,
      id: 5,
      chatTime: 1533260330,
    },
    6: {
      name: '张三',
      info: '/static/imgs/5.jpg',
      type: 0,
      infoType: 0,
      msgType: 1,
      id: 6,
      chatTime: 1533260430,
    },
    7: {
      name: '我',
      info: '/static/audio/1.mp3',
      type: 1,
      infoType: 0,
      msgType: 3,
      id: 7,
      chatTime: 1533260530,
    },
    8: {
      name: '张三',
      info: {
        type: 'video/mp4',
        src: 'http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4',
        poster: 'https://surmon-china.github.io/vue-quill-editor/static/images/surmon-1.jpg',
      },
      type: 0,
      infoType: 0,
      msgType: 4,
      id: 8,
      chatTime: 1533260630,
    },
    9: {
      name: '客服操作',
      info: '客服操作 2018/7/20 星期日',
      infoType: 2,
      id: 9,
      chatTime: 1533260630,
    },
    10: {
      name: '我',
      info: {
        title: '业务信息提醒',
        content:
          '<p>好消息，直播课今晚八点准时开课了，敬请关注</p><p>好消息，直播课今晚八点准时开课了，敬请关注</p>',
      },
      type: 1,
      infoType: 0,
      msgType: 2,
      id: 10,
      chatTime: 1533260730,
    },
    11: {
      name: '我',
      type: 1,
      infoType: 0,
      msgType: 6,
      id: 11,
      chatTime: 1533260730,
      info: [
        {
          info: '/static/imgs/2.jpg',
          title: '进垃圾堆了',
          content: '今山东分局哦我就饿哦极乐世界的富婆视频和教师辅导辅导和',
          msgType: 6,
          infoType: 0,
          id: 111,
        },
        {
          info: '/static/imgs/2.jpg',
          title: '进垃圾堆了',
          content: '是公司鬼斧神工三个都是更好地发挥的好的人同样',
          msgType: 6,
          infoType: 0,
          id: 112,
        },
        {
          info: '/static/imgs/2.jpg',
          title: '进垃圾堆了',
          content: '是公司鬼斧神工三个都是更好地发挥的好的人同样',
          msgType: 6,
          infoType: 0,
          id: 113,
        },
      ],
    },
    12: {
      name: '张三',
      info: '你看见啦水力发电看见路上看见【】士大夫十分立刻哦罚款的说法是防',
      type: 0,
      infoType: 0,
      msgType: 0,
      id: 12,
      chatTime: 1533261730,
    },
    13: {
      name: '张三',
      info: 'https://baidu.com',
      type: 0,
      infoType: 0,
      msgType: 5,
      id: 13,
      chatTime: 1533262730,
    },
    14: {
      name: '系统通知',
      info: '系统通知 2018/7/20 星期日',
      infoType: 3,
      id: 14,
      chatTime: 1533263730,
    },
    15: {
      name: '张三',
      info: '后来我埃里克就是大佛骗我飞机配阿韦杰夫拉开点距离拍摄 怕了科技发达普拉斯飓风琳达设计费',
      type: 0,
      infoType: 0,
      msgType: 0,
      id: 15,
      chatTime: 1533264730,
    },
    16: {
      name: '我',
      info: 'HI,很高兴认识你,HI,很高兴认识你很高兴认识你',
      type: 1,
      infoType: 0,
      msgType: 0,
      id: 16,
      chatTime: 1533205730,
    },
    17: {
      name: '张三',
      info: '安康健身房的饭卡设立了干嘛',
      type: 0,
      infoType: 0,
      msgType: 0,
      id: 17,
      chatTime: 1533215730,
    },
    18: {
      name: '我',
      info: '我也是',
      type: 1,
      msgType: 0,
      id: 18,
      infoType: 1533225730,
    },
    19: {
      name: '我',
      info: 'HI,很高兴认识你,HI,很高兴认识你很高兴认识你',
      type: 1,
      infoType: 0,
      msgType: 0,
      id: 19,
      chatTime: 1533265730,
    },
    20: {
      name: '张三',
      info: '/static/audio/1.mp3',
      type: 0,
      infoType: 0,
      msgType: 3,
      id: 20,
      chatTime: 1533260530,
    },
  },
  chat1: {
    0: {
      name: '张三',
      info: '安康健身房的饭卡设立了干嘛',
      type: 0,
      infoType: 0,
      msgType: 0,
      id: 0,
      chatTime: 1533260010,
    },
    1: {
      name: '我',
      info: '我也是',
      type: 1,
      infoType: 0,
      msgType: 0,
      id: 1,
      chatTime: 1533260020,
    },
  },
  chat2: {
    0: {
      name: '张三',
      info: '安康健身房的饭卡设立了干嘛',
      type: 0,
      infoType: 0,
      msgType: 0,
      id: 0,
      chatTime: 1533260010,
    },
    1: {
      name: '我',
      info: '我也是',
      type: 1,
      infoType: 0,
      msgType: 0,
      id: 1,
      chatTime: 1533260020,
    },
  },
  chat3: {
    0: {
      name: '张三',
      info: '安康健身房的饭卡设立了干嘛',
      type: 0,
      infoType: 0,
      msgType: 0,
      id: 0,
      chatTime: 1533260010,
    },
    1: {
      name: '我',
      info: '我也是',
      type: 1,
      infoType: 0,
      msgType: 0,
      id: 1,
      chatTime: 1533260020,
    },
  },
  chat4: {
    0: {
      name: '张三',
      info: '安康健身房的饭卡设立了干嘛',
      type: 0,
      infoType: 0,
      msgType: 0,
      id: 0,
      chatTime: 1533260010,
    },
    1: {
      name: '我',
      info: '我也是',
      type: 1,
      infoType: 0,
      msgType: 0,
      id: 1,
      chatTime: 1533260020,
    },
  },
  chat5: {
    0: {
      name: '张三',
      info: '安康健身房的饭卡设立了干嘛',
      type: 0,
      infoType: 0,
      msgType: 0,
      id: 0,
      chatTime: 1533260010,
    },
    1: {
      name: '我',
      info: '我也是',
      type: 1,
      infoType: 0,
      msgType: 0,
      id: 1,
      chatTime: 1533260020,
    },
  },
  chat6: {
    0: {
      name: '张三',
      info: '安康健身房的饭卡设立了干嘛',
      type: 0,
      infoType: 0,
      msgType: 0,
      id: 0,
      chatTime: 1533260010,
    },
    1: {
      name: '我',
      info: '我也是',
      type: 1,
      infoType: 0,
      msgType: 0,
      id: 1,
      chatTime: 1533260020,
    },
  },
  chat7: {
    0: {
      name: '张三',
      info: '安康健身房的饭卡设立了干嘛',
      type: 0,
      infoType: 0,
      msgType: 0,
      id: 0,
      chatTime: 1533260010,
    },
    1: {
      name: '我',
      info: '我也是',
      type: 1,
      infoType: 0,
      msgType: 0,
      id: 1,
      chatTime: 1533260020,
    },
  },
  chat8: {
    0: {
      name: '张三',
      info: '安康健身房的饭卡设立了干嘛',
      type: 0,
      infoType: 0,
      msgType: 0,
      id: 0,
      chatTime: 1533260010,
    },
    1: {
      name: '我',
      info: '我也是',
      type: 1,
      infoType: 0,
      msgType: 0,
      id: 1,
      chatTime: 1533260020,
    },
  },
  chat9: {
    0: {
      name: '张三',
      info: '安康健身房的饭卡设立了干嘛',
      type: 0,
      infoType: 0,
      msgType: 0,
      id: 0,
      chatTime: 1533260010,
    },
    1: {
      name: '我',
      info: '我也是',
      type: 1,
      infoType: 0,
      msgType: 0,
      id: 1,
      chatTime: 1533260020,
    },
  },
  chat10: {
    0: {
      name: '张三',
      info: '安康健身房的饭卡设立了干嘛',
      type: 0,
      infoType: 0,
      msgType: 0,
      id: 0,
      chatTime: 1533260010,
    },
    1: {
      name: '我',
      info: '我也是',
      type: 1,
      infoType: 0,
      msgType: 0,
      id: 1,
      chatTime: 1533260020,
    },
  },
  chat11: {
    0: {
      name: '张三',
      info: '安康健身房的饭卡设立了干嘛',
      type: 0,
      infoType: 0,
      msgType: 0,
      id: 0,
      chatTime: 1533260010,
    },
    1: {
      name: '我',
      info: '我也是',
      type: 1,
      infoType: 0,
      msgType: 0,
      id: 1,
      chatTime: 1533260020,
    },
  },
  chat12: {
    0: {
      name: '张三',
      info: '安康健身房的饭卡设立了干嘛',
      type: 0,
      infoType: 0,
      msgType: 0,
      id: 0,
      chatTime: 1533260010,
    },
    1: {
      name: '我',
      info: '我也是',
      type: 1,
      infoType: 0,
      msgType: 0,
      id: 1,
      chatTime: 1533260020,
    },
  },
  chat13: {
    0: {
      name: '张三',
      info: '安康健身房的饭卡设立了干嘛',
      type: 0,
      infoType: 0,
      msgType: 0,
      id: 0,
      chatTime: 1533260010,
    },
    1: {
      name: '我',
      info: '我也是',
      type: 1,
      infoType: 0,
      msgType: 0,
      id: 1,
      chatTime: 1533260020,
    },
  },
  chat14: {
    0: {
      name: '张三',
      info: '安康健身房的饭卡设立了干嘛',
      type: 0,
      infoType: 0,
      msgType: 0,
      id: 0,
      chatTime: 1533260010,
    },
    1: {
      name: '我',
      info: '我也是',
      type: 1,
      infoType: 0,
      msgType: 0,
      id: 1,
      chatTime: 1533260020,
    },
  },
  chat15: {
    0: {
      name: '张三',
      info: '安康健身房的饭卡设立了干嘛',
      type: 0,
      infoType: 0,
      msgType: 0,
      id: 0,
      chatTime: 1533260010,
    },
    1: {
      name: '我',
      info: '我也是',
      type: 1,
      infoType: 0,
      msgType: 0,
      id: 1,
      chatTime: 1533260020,
    },
  },
  chat16: {
    0: {
      name: '张三',
      info: '安康健身房的饭卡设立了干嘛',
      type: 0,
      infoType: 0,
      msgType: 0,
      id: 0,
      chatTime: 1533260010,
    },
    1: {
      name: '我',
      info: '我也是',
      type: 1,
      infoType: 0,
      msgType: 0,
      id: 1,
      chatTime: 1533260020,
    },
  },
  chat17: {
    0: {
      name: '张三',
      info: '安康健身房的饭卡设立了干嘛',
      type: 0,
      infoType: 0,
      msgType: 0,
      id: 0,
      chatTime: 1533260010,
    },
    1: {
      name: '我',
      info: '我也是',
      type: 1,
      infoType: 0,
      msgType: 0,
      id: 1,
      chatTime: 1533260020,
    },
  },
  chat18: {
    0: {
      name: '张三',
      info: '安康健身房的饭卡设立了干嘛',
      type: 0,
      infoType: 0,
      msgType: 0,
      id: 0,
      chatTime: 1533260010,
    },
    1: {
      name: '我',
      info: '我也是',
      type: 1,
      infoType: 0,
      msgType: 0,
      id: 1,
      chatTime: 1533260020,
    },
  },
  chat19: {
    0: {
      name: '张三',
      info: '安康健身房的饭卡设立了干嘛',
      type: 0,
      infoType: 0,
      msgType: 0,
      id: 0,
      chatTime: 1533260010,
    },
    1: {
      name: '我',
      info: '我也是',
      type: 1,
      infoType: 0,
      msgType: 0,
      id: 1,
      chatTime: 1533260020,
    },
  },
  chat20: {
    0: {
      name: '张三',
      info: '安康健身房的饭卡设立了干嘛',
      type: 0,
      infoType: 0,
      msgType: 0,
      id: 0,
      chatTime: 1533260010,
    },
    1: {
      name: '我',
      info: '我也是',
      type: 1,
      infoType: 0,
      msgType: 0,
      id: 1,
      chatTime: 1533260020,
    },
  },
  chat21: {
    0: {
      name: '张三',
      info: '安康健身房的饭卡设立了干嘛',
      type: 0,
      infoType: 0,
      msgType: 0,
      id: 0,
      chatTime: 1533260010,
    },
    1: {
      name: '我',
      info: '我也是',
      type: 1,
      infoType: 0,
      msgType: 0,
      id: 1,
      chatTime: 1533260020,
    },
  },
  chat22: {
    0: {
      name: '张三',
      info: '安康健身房的饭卡设立了干嘛',
      type: 0,
      infoType: 0,
      msgType: 0,
      id: 0,
      chatTime: 1533260010,
    },
    1: {
      name: '我',
      info: '我也是',
      type: 1,
      infoType: 0,
      msgType: 0,
      id: 1,
      chatTime: 1533260020,
    },
  },
  chat23: {
    0: {
      name: '张三',
      info: '安康健身房的饭卡设立了干嘛',
      type: 0,
      infoType: 0,
      msgType: 0,
      id: 0,
      chatTime: 1533260010,
    },
    1: {
      name: '我',
      info: '我也是',
      type: 1,
      infoType: 0,
      msgType: 0,
      id: 1,
      chatTime: 1533260020,
    },
  },
  chat24: {
    0: {
      name: '张三',
      info: '安康健身房的饭卡设立了干嘛',
      type: 0,
      infoType: 0,
      msgType: 0,
      id: 0,
      chatTime: 1533260010,
    },
    1: {
      name: '我',
      info: '我也是',
      type: 1,
      infoType: 0,
      msgType: 0,
      id: 1,
      chatTime: 1533260020,
    },
  },
  chat25: {
    0: {
      name: '张三',
      info: '安康健身房的饭卡设立了干嘛',
      type: 0,
      infoType: 0,
      msgType: 0,
      id: 0,
      chatTime: 1533260010,
    },
    1: {
      name: '我',
      info: '我也是',
      type: 1,
      infoType: 0,
      msgType: 0,
      id: 1,
      chatTime: 1533260020,
    },
  },
  chat26: {
    0: {
      name: '张三',
      info: '安康健身房的饭卡设立了干嘛',
      type: 0,
      infoType: 0,
      msgType: 0,
      id: 0,
      chatTime: 1533260010,
    },
    1: {
      name: '我',
      info: '我也是',
      type: 1,
      infoType: 0,
      msgType: 0,
      id: 1,
      chatTime: 1533260020,
    },
  },
  chat27: {
    0: {
      name: '张三',
      info: '安康健身房的饭卡设立了干嘛',
      type: 0,
      infoType: 0,
      msgType: 0,
      id: 0,
      chatTime: 1533260010,
    },
    1: {
      name: '我',
      info: '我也是',
      type: 1,
      infoType: 0,
      msgType: 0,
      id: 1,
      chatTime: 1533260020,
    },
  },
  chat28: {
    0: {
      name: '张三',
      info: '安康健身房的饭卡设立了干嘛',
      type: 0,
      infoType: 0,
      msgType: 0,
      id: 0,
      chatTime: 1533260010,
    },
    1: {
      name: '我',
      info: '我也是',
      type: 1,
      infoType: 0,
      msgType: 0,
      id: 1,
      chatTime: 1533260020,
    },
  },
  chat29: {
    0: {
      name: '张三',
      info: '安康健身房的饭卡设立了干嘛',
      type: 0,
      infoType: 0,
      msgType: 0,
      id: 0,
      chatTime: 1533260010,
    },
    1: {
      name: '我',
      info: '我也是',
      type: 1,
      infoType: 0,
      msgType: 0,
      id: 1,
      chatTime: 1533260020,
    },
  },
  chat30: {
    0: {
      name: '张三',
      info: '安康健身房的饭卡设立了干嘛',
      type: 0,
      infoType: 0,
      msgType: 0,
      id: 0,
      chatTime: 1533260010,
    },
    1: {
      name: '我',
      info: '我也是',
      type: 1,
      infoType: 0,
      msgType: 0,
      id: 1,
      chatTime: 1533260020,
    },
  },
  chat31: {
    0: {
      name: '张三',
      info: '安康健身房的饭卡设立了干嘛',
      type: 0,
      infoType: 0,
      msgType: 0,
      id: 0,
      chatTime: 1533260010,
    },
    1: {
      name: '我',
      info: '我也是',
      type: 1,
      infoType: 0,
      msgType: 0,
      id: 1,
      chatTime: 1533260020,
    },
  },
  chat32: {
    0: {
      name: '张三',
      info: '安康健身房的饭卡设立了干嘛',
      type: 0,
      infoType: 0,
      msgType: 0,
      id: 0,
      chatTime: 1533260010,
    },
    1: {
      name: '我',
      info: '我也是',
      type: 1,
      infoType: 0,
      msgType: 0,
      id: 1,
      chatTime: 1533260020,
    },
  },
  scrollMore: [
    {
      name: 'Mike',
      info: 'HI,很高兴认识你,HI,很高兴认识你很高兴认识你',
      type: 0,
    },
    {
      name: '我',
      info: '哎呦喂',
      type: 1,
    },
  ],
};
